<a href="https://colab.research.google.com/github/hafizullah25/Machine-Learning-with-Python/blob/master/Data_preprocessing_for_categorical_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
cities = ['Dhaka', 'Cumilla', 'Chittagong', 'Dinajpur', 'Dhaka','Cumilla','Rajshahi']
cities

['Dhaka', 'Cumilla', 'Chittagong', 'Dinajpur', 'Dhaka', 'Cumilla', 'Rajshahi']

In [10]:
from sklearn.preprocessing import LabelEncoder 
encoder = LabelEncoder()
label = encoder.fit_transform(cities)
label 

array([2, 1, 0, 3, 2, 1, 4])

In [30]:
cities = ['Dhaka', 'Cumilla', 'Chittagong', 'Dinajpur', 'Dhaka','Cumilla','Rajshahi']
from sklearn.preprocessing import OneHotEncoder 
import numpy as np 
cities = np.array(cities)
encoder = OneHotEncoder(sparse=False,categories='auto')
cities = cities.reshape(-1,1)
encoder.fit_transform(cities)

array([[0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
import pandas as pd
cities = ['Dhaka', 'Cumilla', 'Chittagong', 'Dinajpur', 'Dhaka','Cumilla','Rajshahi']
cities = pd.get_dummies(cities)
cities

Chittagong  Cumilla  Dhaka  Dinajpur  Rajshahi
0           0        0      1         0         0
1           0        1      0         0         0
2           1        0      0         0         0
3           0        0      0         1         0
4           0        0      1         0         0
5           0        1      0         0         0
6           0        0      0         0         1

In [29]:
cities = ['Dhaka', 'Cumilla', 'Chittagong', 'Dinajpur', 'Dhaka','Cumilla','Rajshahi']
from sklearn.preprocessing import OrdinalEncoder
import numpy as np
cities = np.array(cities)
encoder = OrdinalEncoder()
cities = cities.reshape(-1,1)
cities = encoder.fit_transform(cities)
cities


array([[2.],
       [1.],
       [0.],
       [3.],
       [2.],
       [1.],
       [4.]])